// <auto-generated />
using AlzaProduct.Persistent.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlzaProduct.Persistent.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240921000911_AddProductsSeed")]
    partial class AddProductsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlzaProduct.Persistent.EF.Tables.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgUri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ergonomic wireless mouse with high precision.",
                            ImgUri = "mouse.jpg",
                            Name = "Wireless Mouse",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Mechanical keyboard with RGB lighting.",
                            ImgUri = "keyboard.jpg",
                            Name = "Gaming Keyboard",
                            Price = 79.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "27-inch 4K monitor with IPS panel and ultra-thin bezels.",
                            ImgUri = "monitor.jpg",
                            Name = "4K Monitor",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "6-in-1 USB-C hub with HDMI, USB 3.0, and card reader.",
                            ImgUri = "usbc_hub.jpg",
                            Name = "USB-C Hub",
                            Price = 39.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Over-ear headphones with active noise cancelling and Bluetooth.",
                            ImgUri = "headphones.jpg",
                            Name = "Noise Cancelling Headphones",
                            Price = 199.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "500GB portable SSD with USB 3.1 support.",
                            ImgUri = "ssd.jpg",
                            Name = "Portable SSD",
                            Price = 99.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Waterproof smartwatch with heart rate monitor and GPS.",
                            ImgUri = "smartwatch.jpg",
                            Name = "Smartwatch",
                            Price = 249.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Centralized smart home hub with voice assistant integration.",
                            ImgUri = "smarthub.jpg",
                            Name = "Smart Home Hub",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Portable Bluetooth speaker with 12-hour battery life.",
                            ImgUri = "speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 59.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fast wireless charger compatible with most smartphones.",
                            ImgUri = "wireless_charger.jpg",
                            Name = "Wireless Charger",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Adjustable aluminum laptop stand for better ergonomics.",
                            ImgUri = "laptop_stand.jpg",
                            Name = "Laptop Stand",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Ergonomic gaming chair with lumbar support and adjustable height.",
                            ImgUri = "gaming_chair.jpg",
                            Name = "Gaming Chair",
                            Price = 189.99m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Professional graphics tablet with pen and multi-touch support.",
                            ImgUri = "graphics_tablet.jpg",
                            Name = "Graphics Tablet",
                            Price = 149.99m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Wi-Fi enabled smart thermostat with energy-saving features.",
                            ImgUri = "thermostat.jpg",
                            Name = "Smart Thermostat",
                            Price = 129.99m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Stainless steel electric kettle with temperature control.",
                            ImgUri = "kettle.jpg",
                            Name = "Electric Kettle",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Automatic drip coffee maker with programmable timer.",
                            ImgUri = "coffee_maker.jpg",
                            Name = "Coffee Maker",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 17,
                            Description = "HEPA air purifier with multi-stage filtration and quiet operation.",
                            ImgUri = "air_purifier.jpg",
                            Name = "Air Purifier",
                            Price = 179.99m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Water-resistant fitness tracker with step counting and sleep tracking.",
                            ImgUri = "fitness_tracker.jpg",
                            Name = "Fitness Tracker",
                            Price = 69.99m
                        },
                        new
                        {
                            Id = 19,
                            Description = "4K action camera with waterproof casing and image stabilization.",
                            ImgUri = "action_camera.jpg",
                            Name = "Action Camera",
                            Price = 299.99m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Smart robot vacuum with app control and mapping technology.",
                            ImgUri = "robot_vacuum.jpg",
                            Name = "Robot Vacuum",
                            Price = 399.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
