name: .NET

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "*" ]
    paths-ignore:
      - 'README.md'
      - '*.md' 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Set environment variables
      run: echo "TEST_DATABASE_CONNECTION_STRING=${{ secrets.TESTDATABASECONNECTION }}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      env:
        TEST_DATABASE_CONNECTION_STRING: ${{ secrets.TESTDATABASECONNECTION }}
      run: dotnet test --no-restore --verbosity normal
